purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7662436126265675
  brandStrength: 1
  lightness: 0.8914007705170661
  brandColors:
    - '#11100B'
    - '#5E5F58'
    - '#6F98CF'
    - '#B88341'
    - '#A9B49F'
  rhythmicContrast: 0.4686185233294964
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: ted's test
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7305765
layout_spectrum: 0.2011278
