name: "ted's test"
favicon: null
layout_spectrum: 0.027380599407479167
typography_spectrum: 0.5979014767799526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15157731203362346
  lightness: 0.8914007705170661
  saturation: 0.7662436126265675
  rhythmicContrast: 0.4686185233294964
purpose: []
